# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\work\fjl\LKJ2000-WL\LKJ2000-WL\Graphic\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(543, 437)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(109, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cho_label = QtWidgets.QLabel(self.groupBox_2)
        self.cho_label.setObjectName("cho_label")
        self.horizontalLayout_2.addWidget(self.cho_label)
        spacerItem1 = QtWidgets.QSpacerItem(109, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wl_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.wl_pushButton.setObjectName("wl_pushButton")
        self.horizontalLayout.addWidget(self.wl_pushButton)
        self.stp_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.stp_pushButton.setObjectName("stp_pushButton")
        self.horizontalLayout.addWidget(self.stp_pushButton)
        self.other_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.other_pushButton.setEnabled(False)
        self.other_pushButton.setObjectName("other_pushButton")
        self.horizontalLayout.addWidget(self.other_pushButton)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 23))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.cho_label.setText(_translate("Login", "请选择使用工具类型"))
        self.wl_pushButton.setText(_translate("Login", "无线换装"))
        self.stp_pushButton.setText(_translate("Login", "STP"))
        self.other_pushButton.setText(_translate("Login", "其他"))
