# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 703)
        '''self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_PagType = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_PagType.setObjectName("pushButton_PagType")
        self.verticalLayout_3.addWidget(self.pushButton_PagType)
        self.listWidget_PagType = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget_PagType.setObjectName("listWidget_PagType")
        self.verticalLayout_3.addWidget(self.listWidget_PagType)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_zhen = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_zhen.setObjectName("pushButton_zhen")
        self.verticalLayout_2.addWidget(self.pushButton_zhen)
        self.listWidget_Zhen = QtWidgets.QListWidget(self.layoutWidget1)
        self.listWidget_Zhen.setObjectName("listWidget_Zhen")
        self.verticalLayout_2.addWidget(self.listWidget_Zhen)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_pag = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_pag.setObjectName("pushButton_pag")
        self.verticalLayout.addWidget(self.pushButton_pag)
        self.listWidget_Pag = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidget_Pag.setObjectName("listWidget_Pag")
        self.verticalLayout.addWidget(self.listWidget_Pag)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.Inmenu = QtWidgets.QMenu(self.menuFile)
        self.Inmenu.setObjectName("Inmenu")
        self.Outmenu = QtWidgets.QMenu(self.menuFile)
        self.Outmenu.setObjectName("Outmenu")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.Aboutaction = QtWidgets.QAction(MainWindow)
        self.Aboutaction.setObjectName("Aboutaction")
        self.InactionCan = QtWidgets.QAction(MainWindow)
        self.InactionCan.setObjectName("InactionCan")
        self.InactionLog = QtWidgets.QAction(MainWindow)
        self.InactionLog.setObjectName("InactionLog")
        self.OutactionCan = QtWidgets.QAction(MainWindow)
        self.OutactionCan.setObjectName("OutactionCan")
        self.OutactionLog = QtWidgets.QAction(MainWindow)
        self.OutactionLog.setObjectName("OutactionLog")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_ctrl_f = QtWidgets.QAction(MainWindow)
        self.action_ctrl_f.setObjectName("action_ctrl_f")
        self.Inmenu.addAction(self.InactionCan)
        self.Inmenu.addAction(self.InactionLog)
        self.Outmenu.addAction(self.OutactionCan)
        self.Outmenu.addAction(self.OutactionLog)
        self.menuFile.addAction(self.Outmenu.menuAction())
        self.menuFile.addAction(self.Inmenu.menuAction())
        self.menuFile.addAction(self.action)
        self.menu_H.addAction(self.Aboutaction)
        self.menu_2.addAction(self.action_ctrl_f)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())'''

        self.retranslateUi(MainWindow)
                ##################################################

        ####################################################
        #self.action.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        '''self.pushButton_PagType.setText(_translate("MainWindow", "包类型"))
        self.pushButton_zhen.setText(_translate("MainWindow", "帧数据"))
        self.pushButton_pag.setText(_translate("MainWindow", "包信息"))
        self.menuFile.setTitle(_translate("MainWindow", "文件(F)"))
        self.Inmenu.setTitle(_translate("MainWindow", "内部数据"))
        self.Outmenu.setTitle(_translate("MainWindow", "外部数据"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(H)"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.Aboutaction.setText(_translate("MainWindow", "关于"))
        self.InactionCan.setText(_translate("MainWindow", "can数据"))
        self.InactionLog.setText(_translate("MainWindow", "log日志"))
        self.OutactionCan.setText(_translate("MainWindow", "can数据"))
        self.OutactionLog.setText(_translate("MainWindow", "log日志"))
        self.action.setText(_translate("MainWindow", "退出"))
        self.action_ctrl_f.setText(_translate("MainWindow", "查找"))
        self.action_ctrl_f.setToolTip(_translate("MainWindow", "查找包"))
        self.action_ctrl_f.setShortcut(_translate("MainWindow", "Ctrl+F"))'''
